const NYM_TRANSLATE_LANGUAGES = [
    { code: 'af', name: 'Afrikaans' }, { code: 'sq', name: 'Albanian' },
    { code: 'am', name: 'Amharic' }, { code: 'ar', name: 'Arabic' },
    { code: 'hy', name: 'Armenian' }, { code: 'as', name: 'Assamese' },
    { code: 'ay', name: 'Aymara' }, { code: 'az', name: 'Azerbaijani' },
    { code: 'bm', name: 'Bambara' }, { code: 'eu', name: 'Basque' },
    { code: 'be', name: 'Belarusian' }, { code: 'bn', name: 'Bengali' },
    { code: 'bho', name: 'Bhojpuri' }, { code: 'bs', name: 'Bosnian' },
    { code: 'bg', name: 'Bulgarian' }, { code: 'ca', name: 'Catalan' },
    { code: 'ceb', name: 'Cebuano' }, { code: 'ny', name: 'Chichewa' },
    { code: 'zh', name: 'Chinese (Simplified)' }, { code: 'zh-TW', name: 'Chinese (Traditional)' },
    { code: 'co', name: 'Corsican' }, { code: 'hr', name: 'Croatian' },
    { code: 'cs', name: 'Czech' }, { code: 'da', name: 'Danish' },
    { code: 'dv', name: 'Dhivehi' }, { code: 'doi', name: 'Dogri' },
    { code: 'nl', name: 'Dutch' }, { code: 'en', name: 'English' },
    { code: 'eo', name: 'Esperanto' }, { code: 'et', name: 'Estonian' },
    { code: 'ee', name: 'Ewe' }, { code: 'fil', name: 'Filipino' },
    { code: 'fi', name: 'Finnish' }, { code: 'fr', name: 'French' },
    { code: 'fy', name: 'Frisian' }, { code: 'gl', name: 'Galician' },
    { code: 'ka', name: 'Georgian' }, { code: 'de', name: 'German' },
    { code: 'el', name: 'Greek' }, { code: 'gn', name: 'Guarani' },
    { code: 'gu', name: 'Gujarati' }, { code: 'ht', name: 'Haitian Creole' },
    { code: 'ha', name: 'Hausa' }, { code: 'haw', name: 'Hawaiian' },
    { code: 'he', name: 'Hebrew' }, { code: 'hi', name: 'Hindi' },
    { code: 'hmn', name: 'Hmong' }, { code: 'hu', name: 'Hungarian' },
    { code: 'is', name: 'Icelandic' }, { code: 'ig', name: 'Igbo' },
    { code: 'ilo', name: 'Ilocano' }, { code: 'id', name: 'Indonesian' },
    { code: 'ga', name: 'Irish' }, { code: 'it', name: 'Italian' },
    { code: 'ja', name: 'Japanese' }, { code: 'jv', name: 'Javanese' },
    { code: 'kn', name: 'Kannada' }, { code: 'kk', name: 'Kazakh' },
    { code: 'km', name: 'Khmer' }, { code: 'rw', name: 'Kinyarwanda' },
    { code: 'gom', name: 'Konkani' }, { code: 'ko', name: 'Korean' },
    { code: 'kri', name: 'Krio' }, { code: 'ku', name: 'Kurdish (Kurmanji)' },
    { code: 'ckb', name: 'Kurdish (Sorani)' }, { code: 'ky', name: 'Kyrgyz' },
    { code: 'lo', name: 'Lao' }, { code: 'la', name: 'Latin' },
    { code: 'lv', name: 'Latvian' }, { code: 'ln', name: 'Lingala' },
    { code: 'lt', name: 'Lithuanian' }, { code: 'lg', name: 'Luganda' },
    { code: 'lb', name: 'Luxembourgish' }, { code: 'mk', name: 'Macedonian' },
    { code: 'mai', name: 'Maithili' }, { code: 'mg', name: 'Malagasy' },
    { code: 'ms', name: 'Malay' }, { code: 'ml', name: 'Malayalam' },
    { code: 'mt', name: 'Maltese' }, { code: 'mi', name: 'Maori' },
    { code: 'mr', name: 'Marathi' }, { code: 'mni-Mtei', name: 'Meiteilon (Manipuri)' },
    { code: 'lus', name: 'Mizo' }, { code: 'mn', name: 'Mongolian' },
    { code: 'my', name: 'Myanmar (Burmese)' }, { code: 'ne', name: 'Nepali' },
    { code: 'no', name: 'Norwegian' }, { code: 'or', name: 'Odia (Oriya)' },
    { code: 'om', name: 'Oromo' }, { code: 'ps', name: 'Pashto' },
    { code: 'fa', name: 'Persian' }, { code: 'pl', name: 'Polish' },
    { code: 'pt', name: 'Portuguese' }, { code: 'pa', name: 'Punjabi' },
    { code: 'qu', name: 'Quechua' }, { code: 'ro', name: 'Romanian' },
    { code: 'ru', name: 'Russian' }, { code: 'sm', name: 'Samoan' },
    { code: 'sa', name: 'Sanskrit' }, { code: 'gd', name: 'Scots Gaelic' },
    { code: 'nso', name: 'Sepedi' }, { code: 'sr', name: 'Serbian' },
    { code: 'st', name: 'Sesotho' }, { code: 'sn', name: 'Shona' },
    { code: 'sd', name: 'Sindhi' }, { code: 'si', name: 'Sinhala' },
    { code: 'sk', name: 'Slovak' }, { code: 'sl', name: 'Slovenian' },
    { code: 'so', name: 'Somali' }, { code: 'es', name: 'Spanish' },
    { code: 'su', name: 'Sundanese' }, { code: 'sw', name: 'Swahili' },
    { code: 'sv', name: 'Swedish' }, { code: 'tg', name: 'Tajik' },
    { code: 'ta', name: 'Tamil' }, { code: 'tt', name: 'Tatar' },
    { code: 'te', name: 'Telugu' }, { code: 'th', name: 'Thai' },
    { code: 'ti', name: 'Tigrinya' }, { code: 'ts', name: 'Tsonga' },
    { code: 'tr', name: 'Turkish' }, { code: 'tk', name: 'Turkmen' },
    { code: 'ak', name: 'Twi' }, { code: 'uk', name: 'Ukrainian' },
    { code: 'ur', name: 'Urdu' }, { code: 'ug', name: 'Uyghur' },
    { code: 'uz', name: 'Uzbek' }, { code: 'vi', name: 'Vietnamese' },
    { code: 'cy', name: 'Welsh' }, { code: 'xh', name: 'Xhosa' },
    { code: 'yi', name: 'Yiddish' }, { code: 'yo', name: 'Yoruba' },
    { code: 'zu', name: 'Zulu' },
];

const NYM_TRANSLATE_LANG_NATIVE = (() => {
    const map = {
    'sq': "shqip", 'am': "አማርኛ", 'ar': "العربية",
    'hy': "հայերեն", 'as': "অসমীয়া", 'az': "azərbaycan",
    'bm': "bamanakan", 'eu': "euskara", 'be': "беларуская",
    'bn': "বাংলা", 'bho': "भोजपुरी", 'bs': "bosanski",
    'bg': "български", 'ca': "català", 'ny': "Nyanja",
    'zh': "中文", 'zh-tw': "中文（台灣）", 'hr': "hrvatski",
    'cs': "čeština", 'da': "dansk", 'dv': "Divehi",
    'doi': "डोगरी", 'nl': "Nederlands", 'et': "eesti",
    'ee': "eʋegbe", 'fi': "suomi", 'fr': "français",
    'fy': "Frysk", 'gl': "galego", 'ka': "ქართული",
    'de': "Deutsch", 'el': "Ελληνικά", 'gu': "ગુજરાતી",
    'haw': "ʻŌlelo Hawaiʻi", 'he': "עברית", 'hi': "हिन्दी",
    'hu': "magyar", 'is': "íslenska", 'ilo': "Iloko",
    'id': "Indonesia", 'ga': "Gaeilge", 'it': "italiano",
    'ja': "日本語", 'jv': "Jawa", 'kn': "ಕನ್ನಡ",
    'kk': "қазақ тілі", 'km': "ខ្មែរ", 'rw': "Ikinyarwanda",
    'gom': "कोंकणी", 'ko': "한국어", 'ku': "kurdî (kurmancî)",
    'ckb': "کوردیی ناوەندی", 'ky': "кыргызча", 'lo': "ລາວ",
    'lv': "latviešu", 'ln': "lingála", 'lt': "lietuvių",
    'lb': "Lëtzebuergesch", 'mk': "македонски", 'mai': "मैथिली",
    'ms': "Melayu", 'ml': "മലയാളം", 'mt': "Malti",
    'mi': "Māori", 'mr': "मराठी", 'mni-mtei': "মৈতৈলোন্ (মীতৈ ময়েক)",
    'mn': "монгол", 'my': "မြန်မာ", 'ne': "नेपाली",
    'no': "norsk", 'or': "ଓଡ଼ିଆ", 'om': "Oromoo",
    'ps': "پښتو", 'fa': "فارسی", 'pl': "polski",
    'pt': "português", 'pa': "ਪੰਜਾਬੀ", 'qu': "Runasimi",
    'ro': "română", 'ru': "русский", 'sa': "संस्कृत भाषा",
    'gd': "Gàidhlig", 'nso': "Sesotho sa Leboa", 'sr': "српски",
    'sn': "chiShona", 'sd': "سنڌي", 'si': "සිංහල",
    'sk': "slovenčina", 'sl': "slovenščina", 'so': "Soomaali",
    'es': "español", 'su': "Basa Sunda", 'sw': "Kiswahili",
    'sv': "svenska", 'tg': "тоҷикӣ", 'ta': "தமிழ்",
    'tt': "татар", 'te': "తెలుగు", 'th': "ไทย",
    'ti': "ትግርኛ", 'tr': "Türkçe", 'tk': "türkmen dili",
    'ak': "Akan", 'uk': "українська", 'ur': "اردو",
    'ug': "ئۇيغۇرچە", 'uz': "o‘zbek", 'vi': "Tiếng Việt",
    'cy': "Cymraeg", 'xh': "IsiXhosa", 'yi': "ייִדיש",
    'yo': "Èdè Yorùbá", 'zu': "isiZulu",
    };
    map['zh-cn'] = map['zh'];
    map['iw'] = map['he'];
    map['jw'] = map['jv'];
    return map;
})();

const NYM_TRANSLATE_LANG_NAMES = (() => {
    const map = {};
    for (const l of NYM_TRANSLATE_LANGUAGES) map[l.code.toLowerCase()] = l.name;
    map['zh-cn'] = 'Chinese (Simplified)';
    map['iw'] = 'Hebrew';
    map['jw'] = 'Javanese';
    return map;
})();
