// esbuild entry point — bundles marmot-ts + ts-mls into a single browser-loadable script
import {
  MarmotClient,
  KeyPackageStore,
  GroupStateStore,
  KeyValueGroupStateBackend,
  createGiftWrap,
  getWelcome,
  createWelcomeRumor,
  getWelcomeKeyPackageRefs,
  readWelcomeGroupInfo,
  createGroupEvent,
  decryptGroupMessages,
  serializeApplicationRumor,
  sortGroupCommits,
  createCredential,
  getCredentialPubkey,
  generateKeyPackage,
  getMarmotGroupData,
  serializeClientState,
  deserializeClientState,
  getKeyPackage,
  MarmotGroup,
  Proposals,
} from '@internet-privacy/marmot-ts';

import { defaultCryptoProvider } from 'ts-mls';

// Expose everything globally
window.MarmotMLS = {
  MarmotClient,
  MarmotGroup,
  KeyPackageStore,
  GroupStateStore,
  KeyValueGroupStateBackend,
  createGiftWrap,
  getWelcome,
  createWelcomeRumor,
  getWelcomeKeyPackageRefs,
  readWelcomeGroupInfo,
  createGroupEvent,
  decryptGroupMessages,
  serializeApplicationRumor,
  sortGroupCommits,
  createCredential,
  getCredentialPubkey,
  generateKeyPackage,
  getMarmotGroupData,
  serializeClientState,
  deserializeClientState,
  getKeyPackage,
  Proposals,
  defaultCryptoProvider,
};
